language: go
sudo: false
go:
- 1.8
- tip
before_install:
- openssl aes-256-cbc -K $encrypted_3c9350a46512_key -iv $encrypted_3c9350a46512_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz -C item/creds
- cp ./item/env/config.example ./item/env/config
- go get -u github.com/golang/dep/...
- go get github.com/mattn/goveralls
script:
- dep ensure
- go test -v $(go list ./... | grep -v /vendor)
- goveralls -service=travis-ci
